################################################################################
#
# pytorch-executorch
#
################################################################################

PYTORCH_EXECUTORCH_VERSION = 1.0.0
PYTORCH_EXECUTORCH_SITE = $(call github,pytorch,executorch,v$(PYTORCH_EXECUTORCH_VERSION))
PYTORCH_EXECUTORCH_LICENSE = BSD-3-Clause
PYTORCH_EXECUTORCH_LICENSE_FILES = LICENSE
PYTORCH_EXECUTORCH_INSTALL_STAGING = YES
PYTORCH_EXECUTORCH_INSTALL_TARGET = YES

PYTORCH_EXECUTORCH_DEPENDENCIES = host-cmake host-python3 flatbuffers

PYTORCH_EXECUTORCH_CONF_OPTS = \
	-DEXECUTORCH_BUILD_XNNPACK=OFF \
	-DEXECUTORCH_BUILD_KERNELS_OPTIMIZED=ON \
	-DEXECUTORCH_BUILD_EXTENSION_MODULE=ON \
	-DCMAKE_BUILD_TYPE=Release

# Enable XNNPACK backend
ifeq ($(BR2_PACKAGE_PYTORCH_EXECUTORCH_XNNPACK),y)
PYTORCH_EXECUTORCH_CONF_OPTS += -DEXECUTORCH_BUILD_XNNPACK=ON
endif

# Enable Vulkan backend
ifeq ($(BR2_PACKAGE_PYTORCH_EXECUTORCH_VULKAN),y)
PYTORCH_EXECUTORCH_CONF_OPTS += -DEXECUTORCH_BUILD_VULKAN=ON
endif

$(eval $(cmake-package))

